create or replace database STREAMLIT_APPS;

create or replace schema PUBLIC;

create or replace TABLE CUSTOMER (
	C_CUSTKEY NUMBER(38,0),
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(12,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
);
create or replace TABLE EMPLOYEE (
	EMPID NUMBER(38,0) NOT NULL,
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20),
	EMAIL VARCHAR(25),
	PHONENO VARCHAR(25),
	SALARY NUMBER(38,0),
	primary key (EMPID)
);
create or replace TABLE LINEITEM (
	L_ORDERKEY NUMBER(38,0),
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0),
	L_QUANTITY NUMBER(12,2),
	L_EXTENDEDPRICE NUMBER(12,2),
	L_DISCOUNT NUMBER(12,2),
	L_TAX NUMBER(12,2),
	L_RETURNFLAG VARCHAR(1),
	L_LINESTATUS VARCHAR(1),
	L_SHIPDATE DATE,
	L_COMMITDATE DATE,
	L_RECEIPTDATE DATE,
	L_SHIPINSTRUCT VARCHAR(25),
	L_SHIPMODE VARCHAR(10),
	L_COMMENT VARCHAR(44)
);
create or replace TABLE NATION (
	N_NATIONKEY NUMBER(38,0),
	N_NAME VARCHAR(25),
	N_REGIONKEY NUMBER(38,0),
	N_COMMENT VARCHAR(152)
);
create or replace TABLE ORDERS (
	O_ORDERKEY NUMBER(38,0),
	O_CUSTKEY NUMBER(38,0),
	O_ORDERSTATUS VARCHAR(1),
	O_TOTALPRICE NUMBER(12,2),
	O_ORDERDATE DATE,
	O_ORDERPRIORITY VARCHAR(15),
	O_CLERK VARCHAR(15),
	O_SHIPPRIORITY NUMBER(38,0),
	O_COMMENT VARCHAR(79)
);
create or replace TABLE PARALLEL_1 (
	SR_NO NUMBER(38,0),
	INSRT_TMS TIMESTAMP_NTZ(9)
);
create or replace TABLE PARALLEL_2 (
	SR_NO NUMBER(38,0),
	INSRT_TMS TIMESTAMP_NTZ(9)
);
create or replace TABLE REGION (
	R_REGIONKEY NUMBER(38,0),
	R_NAME VARCHAR(25),
	R_COMMENT VARCHAR(152)
);
create or replace TABLE SUPPLIER (
	S_SUPPKEY NUMBER(38,0),
	S_NAME VARCHAR(25),
	S_ADDRESS VARCHAR(40),
	S_NATIONKEY NUMBER(38,0),
	S_PHONE VARCHAR(15),
	S_ACCTBAL NUMBER(12,2),
	S_COMMENT VARCHAR(101)
);
create or replace TABLE TEST_DEMO (
	COMPANY VARCHAR(16777216),
	COMPANY_NAME VARCHAR(16777216),
	COMPANY_LOCATION VARCHAR(16777216)
);